project_stock/project_stock/urls.py
from django.conf.urls import include, url, handler403, handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from . import views

handler403 = 'project_stock.views.forbidden_request'
handler404 = 'project_stock.views.not_found'
handler500 = 'project_stock.views.bad_request'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^projects/$', views.ProjectListView.as_view(), name='project'),
    url(r'^projects/inactive$', views.InactiveProjectListView.as_view(), name='inactive_project'),
    url(r'^supervisors/$', views.SupervisorListView.as_view(), name='supervisor'),
    url(r'^groups/$', views.GroupListView.as_view(), name='group'),

    url(r'^supervisors/(?P<pk>[0-9]+)', views.SupervisorDetailView.as_view(), name='supervisor'),
    url(r'^projects/(?P<pk>[0-9]+)', views.ProjectDetailView.as_view(), name='project'),
    url(r'^groups/(?P<pk>[0-9]+)', views.GroupDetailView.as_view(), name='group'),

    url(r'^registration/$', views.RegistrationView.as_view(), name='registration'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_stock/project_stock/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.core.files.storage import FileSystemStorage

@python_2_unicode_compatible
class Supervisor(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField()
    website = models.URLField(max_length=128, blank=True, default='')
    location = models.CharField(max_length=128, blank=True, default='') # office
    workplace = models.CharField(max_length=128, blank=True, default='')
    status = models.CharField(max_length=128, blank=True, default='')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=15, blank=True, default='') # validators should be a list
    mobile = models.CharField(validators=[phone_regex], max_length=15, blank=True, default='')
    fax = models.CharField(validators=[phone_regex], max_length=15, blank=True, default='')

    # this is a base64 field. Easy to scrape and link but how to manage from admin page?
    # 2^25 should be about 32MB in characters
    photo = models.TextField(max_length=2**25, blank=True, default='')

    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

@python_2_unicode_compatible
class Project(models.Model):
    supervisor = models.ForeignKey(Supervisor, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=64)
    type_choices = (('B', 'Bachelor project'),
                    ('M', 'Master\'s project'),
                    ('T', 'Master\'s thesis'),
                    ('C', 'Project with compay'),
                    ('O', 'Other'))
    type = models.CharField(max_length=1, choices=type_choices)
    subject = models.CharField(max_length=128, blank=True, default='')
    description_short = models.TextField(max_length=256, blank=True, verbose_name='Short description', default='')
    description_long = models.TextField(blank=True, verbose_name='Long description', default='')
    website = models.URLField(max_length=128, blank=True, default='')
    pub_date = models.DateField(auto_now_add=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    deadline = models.DateField(blank=True, null=True)
    file_upload = models.FileField(upload_to='files/%Y/%m/%d', max_length=100, null=True, blank=True, default='')

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Publication(models.Model):
    author = models.ForeignKey(Supervisor, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.TextField(max_length=128)
    description_short = models.TextField(max_length=256, blank=True, default='')
    description_long = models.TextField(blank=True, default='')
    website = models.URLField(max_length=128, blank=True, default='')
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Group(models.Model):
    members = models.ManyToManyField(Supervisor)
    name = models.CharField(max_length=128)
    subject = models.TextField(max_length=64, blank=True, default='')
    description = models.TextField(blank=True, default='')
    website = models.URLField(max_length=128, blank=True, default='')
    location = models.CharField(max_length=128, blank=True, default='')

    def __str__(self):
        return self.name

project_stock/project_stock/forms.py
from django.forms import ModelForm, FileField
from .models import Supervisor

class PhotoModelForm(ModelForm):
    """A Supervisor Modelform that handles a file upload into memory, converts
       it to base64, and finally saves it into the database as a string
    """
    photo_file = FileField(required=False)

    class Meta:
        model = Supervisor
        exclude = ['photo']

project_stock/project_stock/views.py
from django.shortcuts import render, render_to_response
from .models import Project, Supervisor, Group
from django.views import generic
from django.db.models import Count
from django.utils import timezone
from django.template import RequestContext

def not_found(request):
    response = render_to_response('status/404.html', context_instance=RequestContext(request))
    response.status_code = 404
    return response

def bad_request(request):
    response = render_to_response('status/500.html', context_instance=RequestContext(request))
    response.status_code = 500
    return response

def forbidden_request(request):
    response = render_to_response('status/403.html', context_instance=RequestContext(request))
    response.status_code = 403
    return response

class IndexView(generic.ListView):
    """Index view to be served as the index page"""
    model = Project
    template_name = 'index.html'

    def get_queryset(self):
        return Project.objects.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IndexView, self).get_context_data(**kwargs)
        context['supervisor_list'] = Supervisor.objects.filter(project__deadline__gte=timezone.now()) \
                                                       .annotate(num_projects=Count('project')) \
                                                       .order_by('-num_projects')[0:5]
        context['random_project_list'] = Project.objects.filter(deadline__gte=timezone.now()).order_by('?')[:1]
        context['project_bachelor'] = Project.objects.filter(deadline__gte=timezone.now()).filter(type='B').order_by('-pub_date')[:5]
        context['project_master'] = Project.objects.filter(deadline__gte=timezone.now()).filter(type='M').order_by('-pub_date')[:5]
        context['project_thesis'] = Project.objects.filter(deadline__gte=timezone.now()).filter(type='T').order_by('-pub_date')[:5]
        return context

class ProjectListView(generic.ListView):
    """List view for projects"""
    model = Project
    template_name = 'projects/index.html'

    def get_queryset(self):
        return Project.objects.order_by('name')

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['active_projects'] = Project.objects.filter(deadline__gte=timezone.now()).order_by('-pub_date')
        context['inactive_projects'] = Project.objects.filter(deadline__lte=timezone.now()).exclude(deadline=timezone.now()).order_by('-pub_date')[:25]
        return context

class InactiveProjectListView(generic.ListView):
    """List view of inactive projects"""
    model = Project
    template_name = 'projects/inactive.html'

    def get_queryset(self):
        return Project.objects.filter(deadline__lte=timezone.now()).exclude(deadline=timezone.now()).order_by('-pub_date')

class SupervisorListView(generic.ListView):
    """List view for supervisors"""
    model = Supervisor
    template_name = 'supervisors/index.html'

    def get_queryset(self):
        return Supervisor.objects.order_by('last_name')

class GroupListView(generic.ListView):
    """List view for groups"""
    model = Group
    template_name = 'groups/index.html'

    def get_queryset(self):
        return Group.objects.order_by('name')

class ProjectDetailView(generic.DetailView):
    """View for showing an individual detail page for a project"""
    model = Project
    template_name = 'projects/profile.html'

    def get_context_date(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context['file_upload_list'] = Project.objects.exclude(file_upload__isnull=True)
        return context

class SupervisorDetailView(generic.DetailView):
    """View for showing an individual detail page for a supervisor"""
    model = Supervisor
    template_name = 'supervisors/profile.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SupervisorDetailView, self).get_context_data(**kwargs)
        context['active_projects'] = Project.objects.filter(deadline__gte=timezone.now()).order_by('name')
        context['inactive_projects'] = Project.objects.filter(deadline__lte=timezone.now()).exclude(deadline=timezone.now()).order_by('name')
        context['group_list'] = Group.objects.order_by('id')
        return context

class GroupDetailView(generic.DetailView):
    """View for showing an individual detail page for a group"""
    model = Group
    template_name = 'groups/profile.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        context['supervisor_list'] = Supervisor.objects.order_by('id')
        return context

class RegistrationView(generic.ListView):
    model = Supervisor
    template_name = 'registration/index.html'

    def get_queryset(self):
        return Supervisor.objects.order_by('email')

project_stock/project_stock/templates/projects/inactive.html
{% extends "base.html" %}

{% block title %}Inactive projects{% endblock %}

{% block body %}
<center>
  {% include "search-filter.html" %}
  <table class="data searchable sortable">
    <tr>
      <th>Project</th><th>Type</th><th>Supervisor</th><th>Subject</th><th>Start Date</th><th>End Date</th><th>Deadline</th><th>Published</th>
    </tr>
    {% for p in project_list %}
    <tr class="link" onclick="window.document.location.href='/projects/{{ p.id }}'">
      <td>
        {{ p.name }}
      </td>
      <td>
        {{ p.get_type_display }}
      </td>
      <td>
        {{ p.supervisor }}
      </td>
      <td>
        {{ p.subject }}
      </td>
      <td>
        {{ p.start_date }}
      </td>
      <td>
	{{ p.end_date }}
      </td>
      <td>
        {{ p.deadline }}
      </td>
      <td>
        {{ p.pub_date }}
      </td>
    </tr>
    {% endfor %}
  </table>
</center>
{% endblock %}

project_stock/project_stock/templates/projects/index.html
{% extends "base.html" %}

{% block title %}Projects{% endblock %}

{% block body %}
<center>
  {% include "search-filter.html" %}
  <table class="data searchable sortable">
    <tr>
      <th>Project</th><th>Type</th><th>Supervisor</th><th>Subject</th><th>Start Date</th><th>End Date</th><th>Deadline</th><th>Published</th>
    </tr>
    {% for a in active_projects %}
    <tr class="link" onclick="window.document.location.href='/projects/{{ a.id }}'">
      <td>
        {{ a.name }}
      </td>
      <td>
        {{ a.get_type_display }}
      </td>
      <td>
        {{ a.supervisor }}
      </td>
      <td>
        {{ a.subject }}
      </td>
      <td>
        {{ a.start_date }}
      </td>
      <td>
	{{ a.end_date }}
      </td>
      <td>
        {{ a.deadline }}
      </td>
      <td>
        {{ a.pub_date }}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td>No active projects to show!</td>
    </tr>
    {% endfor %}
  </table>
  <h1>Inactive projects</h1>
  <h3><a href="{% url 'inactive_project' %}">See full list of archived projects here!</a></h3>
  <table class="data searchable sortable">
    <tr>
      <th>Project</th><th>Type</th><th>Supervisor</th><th>Subject</th><th>Start Date</th><th>End Date</th><th>Deadline</th><th>Published</th>
    </tr>
    {% for i in inactive_projects %}
    <tr class="link" onclick="window.document.location.href='/projects/{{ i.id }}'">
      <td>
        {{ i.name }}
      </td>
      <td>
        {{ i.get_type_display }}
      </td>
      <td>
        {{ i.supervisor }}
      </td>
      <td>
        {{ i.subject }}
      </td>
      <td>
        {{ i.start_date }}
      </td>
      <td>
	{{ i.end_date }}
      </td>
      <td>
        {{ i.deadline }}
      </td>
      <td>
        {{ i.pub_date }}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td>No inactive projects to show!</td>
    </tr>
    {% endfor %}
  </table>
</center>
{% endblock %}

project_stock/project_stock/templates/projects/profile.html
{% extends "base.html" %}

{% block title %}{{ project.name }}{% endblock %}

{% block body %}
<center>
  <h1>Project: {{ project.name }}</h1>
  <table class="data">
    <tr>
      <td>Supervisor</td>
      <td><a href="{% url 'supervisor' project.supervisor.id %}">{{ project.supervisor }}</a></td>
    </tr>
    <tr>
      <td>Type</td>
      <td>{{ project.get_type_display }}</td>
    </tr>
    <tr>
      <td>Published</td>
      <td>{{ project.pub_date }}</td>
    </tr>
    <tr>
      <td>Project Start</td>
      <td>{{ project.start_date }}</td>
    </tr>
    <tr>
      <td>Project End</td>
      <td>{{ project.end_date }}</td>
    <tr>
      <td>Project Deadline</td>
      <td>{{ project.deadline }}</td>
    </tr>
    <tr>
      <td>Subject</td>
      <td>{{ project.subject }}</td>
    </tr>
    <tr>
      <td>Website</td>
      <td><a href="{{ project.website }}">{{ project.website }}</a></td>
    </tr>
    <tr>
      <td>Summary</td>
      <td>{{ project.description_short }}</td>
    </tr>
    <tr>
      <td>Description</td>
      <td>{{ project.description_long }}</td>
    </tr>
    {% if project.file_upload %}
    <tr>
      <td>File</td>
      <td><a href="{{ project.file_upload.url }}">{{ project.file_upload.name }} (Size: {{ project.file_upload.size|filesizeformat }})</a></td>
    </tr>
    {% endif %}
    {% endblock %}
  </table>
</center>